import Head from 'next/head';
import styles from 'styles/Home.module.css';
import Link from 'next/link'

const Home = (props) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>react next starter</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to React Next Starter
				</h1>

				<p className={styles.description}>
					Created by React/Redux/Next
				</p>

				<Link href="/chat">
					<button>
						<a>Chat</a>
					</button>
				</Link>
			</main>

			<footer className={styles.footer}>
					Powered by Paddy
			</footer>
		</div>
	);
};

// can preload data in server side
// export const getServerSideProps = wrapper.getServerSideProps(
// 	(store) =>
// 		async ({ pathname, req, res }) => {
//             await store.dispatch(await_function())
//             const count = store.getState().chat.count
// 			return {
// 				props: {
// 					count: count,
// 				},
// 			};
// 		}
// );

export default Home;
